GET http://localhost:5000/inventory/minisgimis

###

GET http://localhost:5000/inventory/minisgimis/0

###


POST http://localhost:5000/inventory/minisgimis
Content-Type: application/json

{
    "userID": "minisgimis",
    "itemID": 1,
    "amount": 420
}

###

PATCH http://localhost:5000/inventory/minisgimis/1
Content-Type: application/json

{
    "amount": 1337
}


###

DELETE http://localhost:5000/inventory/minisgimis/0